package com.learning.test_drools;

import java.util.List;
import java.util.Objects;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Fact2 implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String iden;
	private java.lang.String label;
	private int quantifier1;
	private int quantifier2;
	private java.lang.String quantifier3;
	private java.lang.String idenAlt;
	private List<String> subFacts2;
	private List<SubFact2> intFacts;
	private int totalValue;

	public Fact2() {
	}

	@Override
	public String toString() {
		return "Fact2{" +
				"iden='" + iden + '\'' +
				", label='" + label + '\'' +
				", quantifier1=" + quantifier1 +
				", quantifier2=" + quantifier2 +
				", quantifier3='" + quantifier3 + '\'' +
				", idenAlt='" + idenAlt + '\'' +
				", subFacts2=" + subFacts2 +
				'}';
	}


	public int getTotalValue() {
		return totalValue;
	}

	public void setTotalValue(int totalValue) {
		this.totalValue = totalValue;
	}

	public List<SubFact2> getIntFacts() {
		return intFacts;
	}

	public void setIntFacts(List<SubFact2> intFacts) {
		this.intFacts = intFacts;
	}

	public List getSubFacts2() {
		return subFacts2;
	}

	public void setSubFacts2(List<String> subFacts2) {
		this.subFacts2 = subFacts2;
	}

	public java.lang.String getIden() {
		return this.iden;
	}

	public void setIden(java.lang.String iden) {
		this.iden = iden;
	}

	public java.lang.String getLabel() {
		return this.label;
	}

	public void setLabel(java.lang.String label) {
		this.label = label;
	}

	public int getQuantifier1() {
		return this.quantifier1;
	}

	public void setQuantifier1(int quantifier1) {
		this.quantifier1 = quantifier1;
	}

	public int getQuantifier2() {
		return this.quantifier2;
	}

	public void setQuantifier2(int quantifier2) {
		this.quantifier2 = quantifier2;
	}

	public java.lang.String getQuantifier3() {
		return this.quantifier3;
	}

	public void setQuantifier3(java.lang.String quantifier3) {
		this.quantifier3 = quantifier3;
	}

	public java.lang.String getIdenAlt() {
		return this.idenAlt;
	}

	public void setIdenAlt(java.lang.String idenAlt) {
		this.idenAlt = idenAlt;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) return true;
		if (o == null || getClass() != o.getClass()) return false;
		Fact2 fact2 = (Fact2) o;
		return quantifier1 == fact2.quantifier1 &&
				quantifier2 == fact2.quantifier2 &&
				totalValue == fact2.totalValue &&
				iden.equals(fact2.iden) &&
				Objects.equals(label, fact2.label) &&
				Objects.equals(quantifier3, fact2.quantifier3) &&
				Objects.equals(idenAlt, fact2.idenAlt);
	}

	@Override
	public int hashCode() {
		return Objects.hash(iden, label, quantifier1, quantifier2, quantifier3, idenAlt, totalValue);
	}
}