package com.learning.test_drools;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Fact1 implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Fact1() {
    }




}